Jira api
NetcrackerEducationCenter/data-collector pull request #12
Opened 2020-12-25 08:36 UTC by MajorPayne36

i'm refactored the code and added javadoc comments.

2020-12-27 13:49 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/jira/MyJiraClient.java
> +    private final String DEFAULT_PASS = "IdBigXbJL2aIgrJhGGg2B1A8";
Don't store login/password in the code. Use application.properties at least

2020-12-27 13:51 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/jira/MyJiraClient.java
> +    public Object getIssues() {
Why does the method return Object but not List<BasicProject>?

2020-12-27 13:51 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/jira/MyJiraClient.java
> +    public Object authorize(String uri, String login, String password) {
Same

2020-12-27 13:54 UTC, Rubik0000 commented on pom.xml
> +        <atlassian.fugue.version>2.6.2</atlassian.fugue.version>
Where is this property used? If you want to use properties to define lib version use it everywhere

2020-12-28 17:03 UTC, kravchenko-da requested changes

2020-12-28 17:03 UTC, kravchenko-da commented on src/main/java/org/netcracker/learningcenter/springboot/Controller.java
> +//mport org.springframework.web.servlet.mvc.multiaction.NoSuchRequestHandlingMethodException;
It's usually a bad practice to leave commented code. Consider why you need this, and better to remove or implement related functional. You can always restore it from GIT if needed

2020-12-28 17:03 UTC, kravchenko-da commented on src/main/java/org/netcracker/learningcenter/springboot/Controller.java
> +    @GetMapping("/")
Seems like this method is not really doing anything. If you want to have some "healthcheck" endpoint to see, whether application is up - better to create a separate controller for technical endpoints

2020-12-28 17:03 UTC, kravchenko-da commented on src/main/java/org/netcracker/learningcenter/springboot/Controller.java
> +            return JSONObject.valueToString(list);
Do you really need to cast it to String first?

2020-12-28 17:03 UTC, kravchenko-da commented on src/main/resources/log4j2.xml
> +        <Root level="all">
You can leave only rootlogger, if you don't have any specific settings for other ones. Also, ALL is very excessive level, usually DEBUG is enough

2020-12-28 19:52 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/springboot/Controller.java
> +        if (ticketSystem.toString().equals("jira"))
Compare with enum not with string

2020-12-29 07:07 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/jira/JiraClientWorker.java
> +                e.printStackTrace();
Don't use printStackTrace, put an exception in logger like logger.error("message", e)

2020-12-29 21:10 UTC, Rubik0000 approved these changes

2020-12-30 10:41 UTC, kravchenko-da commented on src/main/java/org/netcracker/learningcenter/jira/JiraClientWorker.java
> +            String PATH_TO_PROPERTIES = "src/main/resources/application.properties";
Only static final class-level variables are named in uppercase

2020-12-30 10:43 UTC, kravchenko-da commented on src/main/java/org/netcracker/learningcenter/jira/JiraClientWorker.java
> +                FileInputStream fileInputStream = new FileInputStream(PATH_TO_PROPERTIES);
Should be changed to
InputStream is = getClass().getClassLoader().getResourceAsStream("application.properties");

Otherwise you are strictly binding yourself to folder structure

2020-12-30 10:43 UTC, kravchenko-da commented on src/main/java/org/netcracker/learningcenter/jira/JiraClientWorker.java
> +            LOGGER.info("Founded project: " + p);
Found :)

2020-12-30 10:45 UTC, kravchenko-da commented on src/main/java/org/netcracker/learningcenter/jira/JiraClientWorker.java
> +            LOGGER.error("Error in authorize() method. Message: ", ex);
You can generally omit writing "message: " in logs, they are formed in a common pattern, where message and stacktrace always have their own place

2020-12-30 10:51 UTC, kravchenko-da commented on src/main/java/org/netcracker/learningcenter/jira/TicketSystems.java
> +    jira
"jira" is a constant instance of enum, and as such - should be named in uppercase according to Java naming conventions. If you need to compare to lowercase value - either use .toLowerCase() or .toUpperCase() respectively, or better implement a getValue() method which will return the same

2021-01-13 16:12 UTC, kravchenko-da approved these changes

2021-01-13 16:27 UTC, merged