changed params in Controller
NetcrackerEducationCenter/data-collector pull request #19
Opened 2021-01-20 18:20 UTC by MajorPayne36

-- Deleted all params and added new JsonNode param.
-- Changed ResurceNotFound exception for better working

2021-01-22 10:30 UTC, Fuzzzi requested changes

2021-01-22 10:30 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/springboot/Controller.java
> +    static String TICKETSYSTEM;
Неиспользуемые статические переменные

2021-01-22 10:30 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/springboot/Controller.java
> +@CrossOrigin(origins = "http://localhost:3000")
вообще по хорошему лучше корс настраивать на в конфиге всего сервиса сразу, но окей, тут пусть будет так, все равно потом, скорее всего он будет ему ненужен.
и почему порт то 3000? есть стандартный порт 8080, пускай приложение на нем работает

2021-01-22 10:30 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/springboot/Controller.java
> +        } catch (Exception ex) {
а зачем нам еще кэтч тут?

2021-01-22 10:30 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/springboot/Controller.java
>  package org.netcracker.learningcenter.springboot;
кстати, перемести пожалуйста немного классы, а то у нас как-то некрасиво.
Контроллеры должны лежать в отдельной папочке для них, а не в одной с самим аппликейшеном. И тоже самое для эксепшенов, должна быть своя отдельная папочка

2021-01-26 12:55 UTC, kravchenko-da approved these changes

2021-01-26 13:22 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/controllers/Controller.java
> +        if (jsonUrl.isMissingNode()) throw new ResourceNotFoundException(URL + " is missing");
Вынеси пожалуйста все эти проверки в отдельную функцию, так будет правильнее и читабельнее

2021-01-26 16:13 UTC, Fuzzzi approved these changes

2021-01-26 16:13 UTC, merged